export const POST_NEW_EVENT_REQUEST = "POST_NEW_EVENT_REQUEST";
export const POST_NEW_EVENT_REQUEST_SUCCESS = "POST_NEW_EVENT_REQUEST_SUCCESS";
export const POST_NEW_EVENT_REQUEST_FAIL = "POST_NEW_EVENT_REQUEST_FAIL";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_REQUEST_SUCCESS = "GET_EVENTS_REQUEST_SUCCESS";
export const GET_EVENTS_REQUEST_FAIL = "GET_EVENTS_REQUEST_FAIL";

export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_REQUEST_SUCCESS = "EDIT_EVENT_REQUEST_SUCCESS";
export const EDIT_EVENT_REQUEST_FAIL = "EDIT_EVENT_REQUEST_FAIL";

export const REMOVE_EVENT_REQUEST = "REMOVE_EVENT_REQUEST";
export const REMOVE_EVENT_REQUEST_SUCCESS = "REMOVE_EVENT_REQUEST_SUCCESS";
export const REMOVE_EVENT_REQUEST_FAIL = "REMOVE_EVENT_REQUEST_FAIL";

export const SHOW_SIDEBAR = "SHOW_SIDEBAR";

export const POST_REQUEST_LOGIN = "POST_REQUEST_LOGIN";
export const POST_REQUEST_SUCCESS_LOGIN = "POST_REQUEST_SUCCESS_LOGIN";
export const POST_REQUEST_ERROR_LOGIN = "POST_REQUEST_ERROR_LOGIN";

export const POST_REQUEST_CHECKIN = "POST_REQUEST_CHECKIN";
export const POST_REQUEST_SUCCESS_CHECKIN = "POST_REQUEST_SUCCESS_CHECKIN";
export const POST_REQUEST_ERROR_CHECKIN = "POST_REQUEST_ERROR_CHECKIN";

export const GET_REQUEST_EVENTS = "GET_REQUEST_EVENTS";
export const GET_REQUEST_SUCCESS_EVENTS = "GET_REQUEST_SUCCESS_EVENTS";
export const GET_REQUEST_ERROR_EVENTS = "GET_REQUEST_ERROR_EVENTS";

export const EDIT_EVENT = "EDIT_EVENT";

export const GET_PHOTOGALARY_REQUEST = "GET_PHOTOGALARY_REQUEST";
export const GET_PHOTOGALARY_REQUEST_SUCCESS = "GET_PHOTOGALARY_REQUEST_SUCCESS";
export const GET_PHOTOGALARY_REQUEST_FAIL = "GET_PHOTOGALARY_REQUEST_FAIL";

export const POST_PHOTOGALARY_REQUEST = "POST_PHOTOGALARY_REQUEST";
export const POST_PHOTOGALARY_REQUEST_SUCCESS = "POST_PHOTOGALARY_REQUEST_SUCCESS";
export const POST_PHOTOGALARY_REQUEST_FAIL = "POST_PHOTOGALARY_REQUEST_FAIL";

export const PUT_PHOTOGALARY_REQUEST = "PUT_PHOTOGALARY_REQUEST";
export const PUT_PHOTOGALARY_REQUEST_SUCCESS = "PUT_PHOTOGALARY_REQUEST_SUCCESS";
export const PUT_PHOTOGALARY_REQUEST_FAIL = "PUT_PHOTOGALARY_REQUEST_FAIL";

export const POST_REGISTRATION_EVENT = "POST_REGISTRATION_EVENT";
export const POST_REGISTRATION_EVENT_SUCCESS = "POST_REGISTRATION_EVENT_SUCCESS";
export const POST_REGISTRATION_EVENT_ERROR = "POST_REGISTRATION_EVENT_ERROR";

export const GET_LOGOUT_USER = "GET_LOGOUT_USER";
export const GET_LOGOUT_USER_SUCCESS = "GET_LOGOUT_USER_SUCCESS";
export const GET_LOGOUT_USER_ERROR = "GET_LOGOUT_USER_ERROR";

export const GET_REQUEST_EVENT_CARD = "GET_REQUEST_EVENT_CARD";
export const GET_REQUEST_SUCCESS_EVENT_CARD = "GET_REQUEST_SUCCESS_EVENT_CARD";
export const GET_REQUEST_ERROR_EVENT_CARD = "GET_REQUEST_ERROR_EVENT_CARD";

export const GET_REQUEST_REVIEWS = "GET_REQUEST_REVIEWS";
export const GET_REQUEST_SUCCESS_REVIEWS = "GET_REQUEST_SUCCESS_REVIEWS";
export const GET_REQUEST_ERROR_REVIEWS = "GET_REQUEST_ERROR_REVIEWS";

export const POST_REQUEST_REVIEW = "POST_REQUEST_REVIEW";
export const POST_REQUEST_SUCCESS_REVIEW = "POST_REQUEST_SUCCESS_REVIEW";
export const POST_REQUEST_ERROR_REVIEW = "POST_REQUEST_ERROR_REVIEW";

export const GET_EVENT_BY_TITLE = "GET_EVENT_BY_TITLE";
export const GET_EVENT_BY_TITLE_SUCCESS = "GET_EVENT_BY_TITLE_SUCCESS";
export const GET_EVENT_BY_TITLE_FAIL = "GET_EVENT_BY_TITLE_FAIL";

export const GET_REGISTRED_USERS = "GET_REGISTRED_USERS";
export const GET_REGISTRED_USERS_SUCCESS = "GET_REGISTRED_USERS_SUCCESS";
export const GET_REGISTRED_USERS_FAIL = "GET_REGISTRED_USERS_FAIL";

export const GET_USERS_INFO = "GET_USERS_INFO";
export const GET_USERS_INFO_SUCCESS = "GET_USERS_INFO_SUCCESS";
export const GET_USERS_INFO_ERROR = "GET_USERS_INFO_ERROR";

export const POST_RESULTS_REQUEST = "POST_RESULTS_REQUEST";
export const POST_RESULTS_REQUEST_SUCCESS = "POST_RESULTS_REQUEST_SUCCESS";
export const POST_RESULTS_REQUEST_FAIL = "POST_RESULTS_REQUEST_FAIL";

export const GET_PHOTOGALARU_EVENTS_REQUEST = "GET_PHOTOGALARU_EVENTS_REQUEST";
export const GET_PHOTOGALARU_EVENTS_REQUEST_SUCCESS = "GET_PHOTOGALARU_EVENTS_REQUEST_SUCCESS";
export const GET_PHOTOGALARU_EVENTS_REQUEST_FAIL = "GET_PHOTOGALARU_EVENTS_REQUEST_FAIL";

export const GET_RESULT = "GET_RESULT";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_ERROR = "GET_RESULT_ERROR";